---
k8s_master:
  hosts:
    node-1:
      ansible_port: 22
      ansible_ssh_host: 158.160.37.91
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
k8s_worker:
  hosts:
    node-2:
      ansible_port: 22
      ansible_ssh_host: 158.160.121.169
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
    node-3:
      ansible_port: 22
      ansible_ssh_host: 158.160.39.13
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
    node-4:
      ansible_port: 22
      ansible_ssh_host: 158.160.59.101
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
    node-5:
      ansible_port: 22
      ansible_ssh_host: 158.160.48.154
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
cluster_srv:
  children:
    k8s_master:
    k8s_worker:
