---
k8s_master:
  hosts:
    node-1:
      ansible_port: 22
      ansible_ssh_host: 62.84.112.83
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
k8s_worker:
  hosts:
    node-2:
      ansible_port: 22
      ansible_ssh_host: 62.84.118.223
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
    node-3:
      ansible_port: 22
      ansible_ssh_host: 62.84.125.197
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
    node-4:
      ansible_port: 22
      ansible_ssh_host: 89.169.136.118
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
    node-5:
      ansible_port: 22
      ansible_ssh_host: 84.252.130.88
      ansible_user: ubuntu
      # ansible_python_interpreter: /usr/bin/python3.12
cluster_srv:
  children:
    k8s_master:
    k8s_worker:
